splsplsh_project/spellweb/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()
admin.site.site_header = 'SpellSplash Administration Area'
admin.site.site_title = 'SpellSplash Admin'

from spellweb import views

urlpatterns = [ 
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'lc/', views.LearnerCreate.as_view(), name='anamedurl'),
    url(r'attempt/', views.attempt_create, name='attcrea'),
    url(r'attemptonebyoneHIDE/', views.attempt_onebyone_createHIDE, name='attemptonebyoneHIDE'),
    url(r'attemptonebyone/', views.WordQuestionListView.as_view(), name='attemptonebyone'),
    url(r'attemptsubmission/', views.attempt_submission, name='attemptsubmission'),
    url(r'showresults/', views.AttemptListView.as_view(), name='displayresults'),
    url(r'testaudio/', views.testaudio, name='testaudio'),
    url(r'testaudiodynamic/', views.WordListView.as_view(), name='testaudiodynamic'),
]

splsplsh_project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from django.views.static import serve
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#url(r'^accounts/', include('auth_urls')),
# Provide static url without leading slash
_static_url = settings.STATIC_URL
if _static_url.startswith('/'):
    _static_url = _static_url[1:]

#url(r'^%s(?P<path>.*)$' % _static_url, serve, {'document_root': settings.STATIC_ROOT}),
urlpatterns = [ 
    url(r'^$', RedirectView.as_view(url='/spellweb/')),
    url(r'^spellweb/', include('spellweb.urls', namespace="spellweb")),
    url(r'^admin/', include(admin.site.urls)),
      #override the default urls
      url(r'^accounts/password/change/$',
                    auth_views.password_change,
                    name='password_change'),
      url(r'^accounts/password/change/done/$',
                    auth_views.password_change_done,
                    name='password_change_done'),
      url(r'^accounts/password/reset/$',
                    auth_views.password_reset,
                    name='password_reset'),
      url(r'^accounts/password/reset/done/$',
                    auth_views.password_reset_done,
                    name='password_reset_done'),
      url(r'^accounts/password/reset/complete/$',
                    auth_views.password_reset_complete,
                    name='password_reset_complete'),
      url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    auth_views.password_reset_confirm,
                    name='auth_password_reset_confirm'),

      #and now add the registration urls
      url(r'^accounts/', include('registration.backends.default.urls')),

]

splsplsh_project/spellweb/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import localtime
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator

ESSENTIALWORDS = 'EW'
NZCER = 'ER'
OTHER = 'OT'
WORDSOURCE_TYPE_CHOICES = (
    (ESSENTIALWORDS, 'Essential Words'),
    (NZCER, 'NZCER'),
    (OTHER, 'OTHER'),
)

MIN_BOX_LEVEL=0
MAX_BOX_LEVEL=4

class Teacher(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    chosen_name = models.CharField(max_length=30)
    family_name = models.CharField(max_length=30)

    class Meta:
        ordering = ['family_name', 'chosen_name']

    def __unicode__(self):
        return u'%s, %s' % (self.family_name, self.chosen_name)

class Learner(models.Model):
    #The username property is a temporary thing until
    #I've worked out how to extend django-registration
    #to do this properly. Clearly the null=True is not good !
    username = models.CharField(max_length=30, null=True)
    teacher = models.ForeignKey(Teacher)
    chosen_name = models.CharField(max_length=30)
    family_name = models.CharField(max_length=30)
    learning_level = models.IntegerField(default=0)
    starting_level = models.IntegerField(default=0)
    source = models.CharField(max_length=2,
                              choices=WORDSOURCE_TYPE_CHOICES,
                              default=ESSENTIALWORDS)

    class Meta:
        ordering = ['family_name', 'chosen_name']

    def __unicode__(self):
        return u'%s, %s' % (self.family_name, self.chosen_name)

class WordManager(models.Manager):
    def after_adding_boxes(self, curr_learner):
        '''
        Returns all `Word` objects for curr_learner
        at the relevant `learning_level`.

        Before it does that it first checks whether all
        corresponding `Box` obects exist and if they do
        not then it cretes them
        '''
        #All boxes for this Learner
        lst_extant_box_id_for_lrnr = Box.objects.filter(
                    learner=curr_learner
                ).values_list('word_id', flat=True)
        print (st_extant_box_id_for_lrnr)


        #Every `Word` up to current level that, for this `Learner`,
        #that doesn't have a `Box`
        words_that_need_boxes = Word.objects.filter(
                    source=curr_learner.source
                ).filter(
                    level__lte=curr_learner.learning_level
                ).exclude(
                    id__in=lst_extant_box_id_for_lrnr
                )
        #Add a `Box` for each `Word` that doesn't have one
        lst_boxes = []
        for wrd in words_that_need_boxes:
            lst_boxes.append(Box(learner=curr_learner, word=wrd, box_number=MIN_BOX_LEVEL))

        print("About to insert {0} 'Boxes' for 'Learner' : {1}".format(len(lst_boxes), curr_learner))

        Box.objects.bulk_create(lst_boxes)

        #Now return the 'normal' `Word` QS
        wordQS = Word.objects.filter(
                    source=curr_learner.source
                ).filter(
                    level__lte=curr_learner.learning_level
                )

        return wordQS


class Word(models.Model):
    objects = WordManager()

    level = models.IntegerField()
    word = models.CharField(max_length=30)
    source = models.CharField(max_length=2,
                              choices=WORDSOURCE_TYPE_CHOICES,
                              default=ESSENTIALWORDS)
    hint = models.CharField(max_length=100, null=True, blank=True)
    soundsource = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ['level', 'word']
        unique_together = (("source", "word"),)

    def __unicode__(self):
        return self.word

    @property
    def has_hint(self):
        return self.hint is not None and self.hint.strip() != ""

    @property
    def has_soundsource(self):
        return self.soundsource is not None and self.soundsource.strip() != ""
    

class Attempt(models.Model):
    '''
    `Attempt` represents an occassion when a `Learner`
    has been asked to spell a `Word`.

    The results and time of the `Attempt` are recorded
    '''
    learner = models.ForeignKey(Learner)
    word = models.ForeignKey(Word)
    when = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=False)

    class Meta:
        ordering = ['-when']

    def __unicode__(self):
        formatted_when = localtime(self.when).strftime('%d-%b-%Y %X')
        if self.success:
            formatted_success = "YES"
        else:
            formatted_success = "NO"

        return u'%s - %s- Success ?: %s ' % (self.word, formatted_when, formatted_success)


class Box(models.Model):
    '''
    `Box` represents a "Box" in the sense of the Leitner system of improving
    the use of flashcards.

    A predetermined number of boxes are used. If the `Learner` is able to
    correctly spell a `Word` the `Word` moves up to a higher level `Box`; 
    if they fail to spell a `Word` the `Word` moves down a level.

    When we are selecting a group of `Word` objects using the Leitner system
    words that appear in a lower level `Box` are more likely to be selected
    '''
    class Meta:
        verbose_name_plural = "Boxes"

    learner = models.ForeignKey(Learner)
    word = models.ForeignKey(Word)
    box_number = models.IntegerField(validators=[MinValueValidator(MIN_BOX_LEVEL), 
                                                 MaxValueValidator(MAX_BOX_LEVEL)])

    def update_box_number(self, result):
        '''
        Updates the `box_number` property - upwards if `result` is True, downwards
        if `result` is False - unless `box_number is already at the end of the valid
        range in which case it does nothing
        '''
        assert ((result==False) or (result==True))

        if result:
            if self.box_number < MAX_BOX_LEVEL:
                self.box_number += 1
                self.save()
        else:
            if self.box_number > MIN_BOX_LEVEL:
                self.box_number -= 1
                self.save()

    def __unicode__(self):
        return unicode(self.learner) + unicode(' has word "')  + unicode(self.word) + unicode('" in box:') + unicode(self.box_number)

splsplsh_project/spellweb/forms.py
# forms.py
from django.forms import ModelForm, Form, CharField, BooleanField, TextInput
from django.forms.models import inlineformset_factory, ModelForm

from .models import Learner, Word, Attempt 

class AttemptForm(Form):

    word = CharField(required=False)
    success = BooleanField(required=False)
    wordid = CharField()

splsplsh_project/templates/spellweb/attempt_add.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}


<form method="post" action="{% url 'spellweb:attemptsubmission' %}">
{% csrf_token %}
    <fieldset>
         <legend>Record your Attempts</legend>
        {{ formset.management_form }}
        <table>
        {% for form in formset %}
        <tr>
            <td>{{ form.word.value }}</td>
            {% if form.hint.strip %}
                <td>({{ form.hint.value }})</td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            <td>
                <label for="{{ form.success.id_for_label }}">Success?:</label> 
                <input id="{{ form.success.id_for_label }}" name="{{ form.success.html_name }}" type="checkbox" />
            <span>
            <input id="{{ form.wordid.id_for_wordid }}" name="{{ form.wordid.html_name }}" type="hidden" value="{{ form.wordid.value }}" />
            </td>
            </span>
            </p>
        </tr>
        {% endfor %}
        </table>
    </fieldset>
    <input class="spspbutton" type="submit" value="Submit Your Results" />
    <a href="{% url 'spellweb:index' %}"><button class="spspbutton" type="button">Cancel</button></a>
</form>
{% endblock %}

splsplsh_project/templates/spellweb/attempt_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% csrf_token %}

<h1>Attempts</h1>
<a href="{% url 'spellweb:attcrea'  %}">Keep practicing your spelling by clicking here</a>
<table>
{% for attempt in object_list %}
    <tr>
        <td>
            {{ attempt.word.word }}
        </td>
        <td>
            {{ attempt.when|date }} {{ attempt.when|time }}</li>
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan=2>
            No attempts yet.
        </td>
    </tr>
{% endfor %}
</table>



{% endblock %}

splsplsh_project/templates/spellweb/attempt_onebyone_add.html
{% extends "basebootstrap.html" %}
{% load i18n %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.1/howler.core.min.js"></script>
    <script>
    var sound = new Howl({
        src: ['https://s3-us-west-1.amazonaws.com/spellsplash/banana.mp3']
    });
    sound.play();

    var arrUrl = [];
    {% for word in object_list %}
    arrUrl.push('{{ word.soundsource }}')
    {% endfor %}

    </script>
{% endblock %}

{% block content %}


<form class="form-inline">
  <div class="form-group">
    <label for="spellingattempt">Spell the word here</label>
    <input type="text" class="form-control" id="spellingattempt" placeholder="Type your spelling here ...">
  </div>
  <button type="listenagain" class="btn btn-info spaceitleft">Listen Again</button>
  <button type="submit" class="btn btn-primary spaceitleft">Submit</button>
</form>

<div id="hiddenattemptform">
    <form method="post" action="{% url 'spellweb:attemptsubmission' %}">
    {% csrf_token %}
        <fieldset>
             <legend>Record your Attempts</legend>
            {{ formset.management_form }}
            <table>
            {% for form in formset %}
            <script>
                arrUrl.push('{{ word.soundsource }}')
            </script>
            <tr>
                <td>{{ form.word.value }}</td>
                {% if form.hint.strip %}
                    <td>({{ form.hint.value }})</td>
                {% else %}
                    <td>&nbsp;</td>
                {% endif %}
                <td>
                    <label for="{{ form.success.id_for_label }}">Success?:</label> 
                    <input id="{{ form.success.id_for_label }}" name="{{ form.success.html_name }}" type="checkbox" />
                <span>
                <input id="{{ form.wordid.id_for_wordid }}" name="{{ form.wordid.html_name }}" type="hidden" value="{{ form.wordid.value }}" />
                </td>
                </span>
                </p>
            </tr>
            {% endfor %}
            </table>
        </fieldset>
        <input class="spspbutton" type="submit" value="Submit Your Results" />
        <a href="{% url 'spellweb:index' %}"><button class="spspbutton" type="button">Cancel</button></a>
    </form>
</div>
{% endblock %}

splsplsh_project/templates/spellweb/attempt_onebyone_api_add.html
{% extends "basebootstrap.html" %}
{% load i18n %}

{% block title %}{{ html_header_page_title }}{% endblock %}

{% block head %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.1/howler.core.min.js"></script>
    <script>

    (function($) {
        var SPS = SPS || function () { };
        SPS.ATO = function () {
            var myPrivateVar;
            myPrivateVar = 0;          
            aPrivateFunc0 = function(){
                myPrivateVar += 1;
                return true;
            };
            return {
                sprintf: function (format, etc) {
                    //A simple sprintf-a-like. It only handles strings
                    //
                    //Seen at : http://stackoverflow.com/a/4795914/61340
                    var arg = arguments;
                    var i = 1;
                    return format.replace(/%((%)|s)/g, function (m) { return m[2] || arg[i++] });
                },
                clntSdWrd: function(word, soundsource, attempt, hint) {
                    this.word = word;
                    this.soundsource = soundsource;
                    this.attempt = attempt;
                    this.hint = hint;
                },
                //An array of `clntSdWrd` objects
                arrWord : [],
                //An index into `arrWord` showing which word
                //is currently being presented to the user
                idxWord : null,
                listenAgainButtonClickHandlerFactory : function(){
                    return (function (event) {
                        SPS.ATO.playCurrentSound();
                        return false;
                    });
                },
                submitButtonClickHandlerFactory : function(){
                    return (function (event) {
                        SPS.ATO.arrWord[SPS.ATO.idxWord].attempt = $('#spellingattempt').val().toLowerCase().trim();
                        $('#spellingattempt').val("");
                        $("#spellingattempt").focus();
                        SPS.ATO.setupNextScreen();
                        return false;
                    });
                },
                setupNextScreen: function( ) {
                    SPS.ATO.idxWord = SPS.ATO.idxWord + 1;
                    if (SPS.ATO.idxWord >= this.arrWord.length){
                        alert("That's all folks");
                    }else{
                        var visibleIdx = SPS.ATO.idxWord + 1;
                        $("#progressmsg").html(this.sprintf("%s of %s Questions", visibleIdx.toString(), this.arrWord.length.toString())); 
                        if (SPS.ATO.arrWord[SPS.ATO.idxWord].hint === null){
                            $('#wordhintpanel').hide();
                        }else{
                            $('#wordhintpanel > .panel-body').html(SPS.ATO.arrWord[SPS.ATO.idxWord].hint);
                            $('#wordhintpanel > .panel-body').css("color","Red");
                            $('#wordhintpanel').show();
                        }
                        console.log("setupNextScreen - SPS.ATO.idxWord = " + SPS.ATO.idxWord);
                        this.playCurrentSound();
                    }
                },
                initalizeBaseScreen: function( ) {
                    SPS.ATO.idxWord = -1;
                    $('#listenagain').bind("click", this.listenAgainButtonClickHandlerFactory());
                    $('#submitattempt').bind("click", this.submitButtonClickHandlerFactory());
                },
                initalizeLocalDataStore: function( ) {
                    var hint;
                    var soundsource;
                    {% for word in object_list %}
                    {% if word.has_hint %}
                    hint = '{{word.hint}}';
                    {% else %}
                    hint = null;
                    console.log(this.sprintf("%s has no hint", "{{ word.word }}"));
                    {% endif %} 
                    {% if word.has_soundsource %}
                    soundsource = '{{word.soundsource}}';
                    {% else %}
                    soundsource = null;
                    console.log(this.sprintf("%s has no soundsource", "{{ word.word }}"));
                    {% endif %} 
                    var newWord = new this.clntSdWrd('{{ word.word }}', soundsource, null, hint);
                    this.arrWord.push(newWord);
                    {% endfor %}
                },
                playCurrentSound: function( ) {
                    console.log("playCurrentSound A - SPS.ATO.idxWord = " + SPS.ATO.idxWord);
                    console.log("playCurrentSound B - SPS.ATO.arrWord[SPS.ATO.idxWord].soundsource = " + SPS.ATO.arrWord[SPS.ATO.idxWord].soundsource);
                    console.log("playCurrentSound C - this.arrWord[SPS.ATO.idxWord].soundsource = " + this.arrWord[SPS.ATO.idxWord].soundsource);
                    var sound = new Howl({
                        src: [this.arrWord[SPS.ATO.idxWord].soundsource]
                    });
                    sound.play();
                },

            };
        }();

        $(document).ready(function() {
            SPS.ATO.initalizeLocalDataStore();
            SPS.ATO.initalizeBaseScreen();
            SPS.ATO.setupNextScreen();
        });
    })(jQuery);


    </script>
{% endblock %}

{% block content %}




<form class="form-inline spspsubmitattempt spaceabove5em" action=''>
  <div class="form-group">
    <label for="spellingattempt">Type the word you can hear </label>
    <input type="text" class="form-control" id="spellingattempt" placeholder="Type your spelling here ...">
  </div>
  <button type="button" id="submitattempt" class="btn btn-primary spaceitleft">Submit</button>
    <button type="button" id="listenagain" class="btn btn-info spaceitleft spaceitright pull-right">Listen To The Word Again</button>
</form>
<div class="panel panel-default spaceabove5em" id="wordhintpanel">
    <div class="panel-heading">Below is an example of how the word might be used</div>
    <div class="panel-body" id="wordhintpanelcontent"></div>
</div>
<h3 id="progressmsg" class="text-right spaceabove5em"></h3>


{% endblock %}

splsplsh_project/templates/spellweb/attempt_submission_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>Good Try !</h2>
<p>
    You've submitted your attempt.
</p>
<p>
    <a href="{% url 'spellweb:displayresults' %}">{% trans "View your results so far" %}</a>  
</p>
{% endblock %}

splsplsh_project/templates/spellweb/index.html
{% extends "basebootstrap.html" %}
{% load i18n %}

{% block content %}
<h2>Welcome to Spellsplash !</h2>
<p>You are at learning level : {{ lrng_lvl }} using the word set : {{ word_set }}</p> 
<p class="lead"><a href="{% url 'spellweb:attemptonebyone' %}">Keep practicing your spelling by clicking here</a></p> 
{% endblock %}

splsplsh_project/templates/spellweb/learner_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <fieldset>
         <legend>Provide your Learner Profile</legend>
    {{ form.as_p }}
    </fieldset>
    <input class="spspbutton" type="submit" value="Create" />
</form>

{{ test_message }}
{{ test_uname }}
{% endblock %}

splsplsh_project/templates/spellweb/testaudio.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.1/howler.core.min.js"></script>
    <script>
    var sound = new Howl({
        src: ['http://ssl.gstatic.com/dictionary/static/sounds/de/0/study.mp3']
    });
    sound.play();
    </script>
{% endblock %}

{% block content %}
    <h2>Spellsplash Audio Test</h2>
     <p>Plays a remote audio using the howler js library.</p> 
{% endblock %}

splsplsh_project/templates/spellweb/testaudiodynamic.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.1/howler.core.min.js"></script>
    <script>
    var sound = new Howl({
        src: ['https://s3-us-west-1.amazonaws.com/spellsplash/banana.mp3']
    });
    sound.play();

    var arrUrl = [];
    {% for word in object_list %}
    arrUrl.push('{{ word.soundsource }}')
    {% endfor %}

    </script>
{% endblock %}

{% block content %}
    <h2>Spellsplash Audio Test</h2>
     <p>Plays a remote audio using the howler js library.</p> 
     <table>
    {% for word in object_list %}
        <tr>
            <td>
                {{ word.word }}
            </td>
            <td>
                {{ word.soundsource }}</li>
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan=2>
                No attempts yet.
            </td>
        </tr>
    {% endfor %}
     </table>
{% endblock %}